Repository be14-fin-Clover-Salad/be14-fin-Clover-Salad-FE, pull requests merged in 2025-06, with the labels that each got.

#96 [Env] 공통 레이아웃 수정
  public/logo_text.svg
  public/salad_text.png
  src/components/Header.vue
  src/config/menuConfig.js
Labels: enhancement

#98 [Feat] 공지사항 목록 조회 기능 구현
  .github/workflows/cr.yml
  db.json
  src/components/common/Pagination.vue
  src/components/notice/NoticeList.vue
  src/config/menuConfig.js
  src/views/support/notice/NoticeDetail.vue
  src/views/support/notice/NoticeView.vue
Labels: enhancement

#101 [Feat] 로그인 및 로그아웃 기능 구현
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/api/auth.js
  src/components/Header.vue
  src/components/notice/NoticeList.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/views/user/LoginView.vue
Labels: enhancement

#103 [Feature] 공통 컴포넌트 데이터 테이블 구현
  src/components/BaseDataTable.vue
  src/config/menuConfig.js
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#104 [Feat] 공지사항 작성 기능 구현
  db.json
  package-lock.json
  package.json
  src/components/notice/AddTargetModal.vue
  src/components/notice/NoticeList.vue
  src/main.js
  src/router/index.js
  src/views/support/notice/NoticeCreate.vue
  src/views/support/notice/NoticeDetail.vue
Labels: enhancement

#108 [Feat] 고객 정보 상세 화면 구현 및 라우터 설정
  src/config/menuConfig.js
  src/router/index.js
  src/views/customer/CustomerDetail.vue
  src/views/customer/CustomerTable.vue
Labels: enhancement

#111 [Feat] 로그인 시 헤더 스타일 변경 및 마이페이지 구현
  public/logout.svg
  public/notification.svg
  public/profile.svg
  src/api/auth.js
  src/components/Breadcrumb.vue
  src/components/Header.vue
  src/components/TopTabs.vue
  src/config/menuConfig.js
  src/router/index.js
  src/stores/auth.js
  src/views/user/LoginView.vue
  src/views/user/Mypage.vue
  src/views/user/ResetPassword.vue
Labels: enhancement

#115 [Refactor] 리프레시 토큰 재발급 요청 실패 시 무한 루프 문제 해결
  src/api/auth.js
  src/stores/auth.js
  src/views/user/LoginView.vue
Labels: bug

#117 [Feat] 문의사항 CRUD 기능 구현
  db.json
  src/components/notice/NoticeList.vue
  src/components/qna/QnaList.vue
  src/config/menuConfig.js
  src/router/index.js
  src/views/support/notice/NoticeCreate.vue
  src/views/support/notice/NoticeDetail.vue
  src/views/support/notice/NoticeEdit.vue
  src/views/support/qna/QnaCreate.vue
  src/views/support/qna/QnaDetail.vue
  src/views/support/qna/QnaView.vue
Labels: enhancement

#121 [Feature] 계약 페이지 구현
  src/components/common/SearchFilterShell.vue
  src/components/contract/ContractSearchFields.vue
  src/views/contract/ContractManagementView.vue
  vite.config.js
Labels: enhancement

#124 [Refactor] 데이터 테이블 수정
  src/components/BaseDataTable.vue
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#126 [Refactor] 로그인 상태 관리 기능 수정
  src/components/Header.vue
  src/main.js
  src/stores/auth.js
Labels: bug, enhancement

#127 [Feature] 계약 등록 페이지 구현
  src/api/auth.js
  src/components/BaseDataTable.vue
  src/components/Header.vue
  src/components/contract/ContractDetailModal.vue
  src/components/contract/ContractUploadSuccessModal.vue
  src/views/contract/ContractManagementView.vue
  src/views/contract/ContractUploadModal.vue
Labels: enhancement

#135 [Feat] 결재 조회, 처리 기능 구현
  package.json
  src/api/auth.js
  src/components/approval/ApprovalDetailModal.vue
  src/components/approval/ApprovalSearchFields.vue
  src/config/menuConfig.js
  src/main.js
  src/views/approval/Approval.vue
Labels: enhancement

#137 [Feat] 부서(팀) 조회, 부서별 사원 조회, 사원 상세 조회, 사원 조건 검색 기능 구현
  public/defaultFolder.svg
  public/openedFolder.svg
  src/components/employee/DepartmentTreeNode.vue
  src/components/employee/EmployeeDepartmentList.vue
  src/components/employee/EmployeeDetail.vue
  src/components/employee/EmployeeSearchFields.vue
  src/config/menuConfig.js
  src/stores/departmentStore.js
  src/views/employee/EmployeeLayout.vue
Labels: enhancement

#146 [Refactor] 로그인 로직 일부 개선
  src/components/employee/EmployeeDepartmentList.vue
  src/components/employee/EmployeeSearchResult.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/views/employee/EmployeeLayout.vue
  src/views/notification/NotificationLayout.vue
Labels: enhancement

#142 [Feat] 사원 검색 모달창 컴포넌트 구현
  src/components/employee/EmployeeDepartmentList.vue
  src/components/employee/EmployeeSearchResult.vue
  src/views/employee/EmployeeLayout.vue
Labels: enhancement

#143 [Feat] 상품 도메인 인쇄 기능 제외 완성
  src/components/product/ImageUploadModal.vue
  src/components/product/ProductDeleteConfirmModal.vue
  src/components/product/ProductDetailForm.vue
  src/components/product/ProductRegisterCancelModal.vue
  src/components/product/ProductRegisterConfirmModal.vue
  src/components/product/ProductRegisterForm.vue
  src/components/product/ProductSearchFields.vue
  src/config/menuConfig.js
  src/router/index.js
  src/views/product/ProductDetail.vue
  src/views/product/ProductList.vue
  src/views/product/ProductRegister.vue
  src/views/product/ProductUpdate.vue
Labels: enhancement

#147 [Feat] : 계약서 양식 페이지 구현 및 공통 컴포넌트 수정
  src/components/BaseDataTable.vue
  src/components/common/SearchFilterShell.vue
  src/components/contract/ContractDetailModal.vue
  src/components/contract/ContractSearchFields.vue
  src/config/menuConfig.js
  src/views/contract/ContractManagementView.vue
  src/views/contractTemplate/ContractTemplateDetailModal.vue
  src/views/contractTemplate/ContractTemplateSearchFields.vue
  src/views/contractTemplate/ContractTemplateUploadModal.vue
  src/views/contractTemplate/ContractTemplateUploadSuccessModal.vue
  src/views/contractTemplate/ContractTemplateView.vue
Labels: enhancement

#153 [Fix] 상품 관리에서 상단 탭 종료 시 홈으로 돌아가지 않는 문제 수정
  src/router/index.js
Labels: bug

#156 [Feat] 영업부 매출 관리 대시보드 페이지 및 기능 구현
  package.json
  src/components/salesDashboard/MonthQuarterSalesCard.vue
  src/components/salesDashboard/TeamSalesBarChart.vue
  src/components/salesDashboard/YearSalesCard.vue
  src/components/salesDashboard/YearlySalesLineChart.vue
  src/config/menuConfig.js
  src/layouts/DefaultLayout.vue
  src/main.js
  src/views/salesDashboard/SalesDashboardLayout.vue
Labels: enhancement

#158 [Feat] 공지사항과 문의사항 등록시 알림 생성
  src/main.js
Labels: enhancement

#160 [Refactor] SSE 알림 발생 시점을 명확하게 하기 위해 앱 마운트 리팩토링
  src/main.js
Labels: bug, enhancement

#161 [Refactor] : 여러가지 자잘한 기능 수정
  src/components/contract/ContractSearchFields.vue
  src/layouts/DefaultLayout.vue
  src/views/contract/ContractManagementView.vue
  src/views/contract/ContractReplaceModal.vue
  src/views/salesDashboard/SalesDashboardLayout.vue
Labels: enhancement

#163 [Refactor] 매출 관리의 관리자 페이지 ui 일부 개선
  src/components/sales/SalesSearchFields.vue
  src/router/index.js
  src/views/sales/RegisterSales.vue
  src/views/sales/SalesView.vue
  src/views/salesDashboard/SalesDashboardLayout.vue
Labels: enhancement

#166 [Refactor] 로그인 - 액세스 토큰 저장방식 변경 및 헤더 드롭다운 ui/ux 일부 개선
  src/components/Header.vue
  src/components/employee/EmployeeDepartmentList.vue
  src/components/notice/NoticeList.vue
  src/components/qna/QnaList.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/stores/notification.js
  src/views/approval/Approval.vue
  src/views/employee/EmployeeLayout.vue
  src/views/notification/NotificationLayout.vue
  src/views/sales/RegisterSales.vue
  src/views/sales/SalesView.vue
  src/views/support/notice/NoticeCreate.vue
  src/views/support/notice/NoticeDetail.vue
  src/views/support/notice/NoticeEdit.vue
  src/views/support/qna/QnaCreate.vue
  src/views/support/qna/QnaDetail.vue
  src/views/user/Mypage.vue
  src/views/user/ResetPassword.vue
Labels: enhancement

#168 마이페이지에서 프로필 사진 업데이트 시 S3에 사진을 저장하고 내 프로필 사진이 업데이트되도록 구현
  src/views/user/Mypage.vue
Labels: enhancement

#171 [Refactor] 파일 업로드 변경에 따른 페이지 수정
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#174 [Feat] 사이드바와 탭 영역 스타일 변경
  public/search.svg
  src/components/Header.vue
  src/components/Sidebar.vue
  src/components/TopTabs.vue
  src/main.js
  src/stores/tabStore.js
Labels: enhancement

#178 [Env] 프론트 배포 설정
  .github/workflows/deploy.yml
  Procfile
  package.json
  server.js
  src/api/auth.js
  vite.config.js
Labels: enhancement

#179 [Refactor] : 계약 관련 수정
  src/components/contract/ContractDetailModal.vue
  src/views/contract/ContractApprovalRequestModal.vue
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#177 [Feature] 실적 목표 관련 페이지 구현
  src/components/goal/DepartmentGoalSearchFields.vue
  src/components/goal/EmployeeGoalDeleteModal.vue
  src/components/goal/EmployeeGoalSearchFields.vue
  src/components/goal/GoalRegisterCancelModal.vue
  src/components/goal/GoalRegisterConfirmModal.vue
  src/config/menuConfig.js
  src/router/index.js
  src/views/goal/DepartmentGoalList.vue
  src/views/goal/EmployeeGoalDetail.vue
  src/views/goal/EmployeeGoalList.vue
  src/views/goal/EmployeeGoalRegister.vue
  src/views/goal/EmployeeGoalUpdate.vue
  src/views/product/ProductList.vue
Labels: enhancement

#182 [Env] 배포용 수정사항 develop 반영
  package.json
  server.js
  src/api/auth.js
  src/components/Sidebar.vue
Labels: enhancement

#184 [Refactor] 전반적인 스타일 수정 및 버그 픽스
  src/components/Header.vue
  src/components/approval/ApprovalDetailModal.vue
  src/components/approval/ApprovalSearchFields.vue
  src/components/common/SearchFilterShell.vue
  src/components/contract/ContractDetailModal.vue
  src/components/contract/ContractSearchFields.vue
  src/components/employee/EmployeeDepartmentList.vue
  src/components/employee/EmployeeSearchFields.vue
  src/components/notice/NoticeList.vue
  src/components/product/ProductSearchFields.vue
  src/components/qna/QnaList.vue
  src/components/sales/SalesSearchFields.vue
  src/stores/notification.js
  src/views/approval/Approval.vue
  src/views/contract/ContractApprovalRequestModal.vue
  src/views/contract/ContractManagementView.vue
  src/views/contractTemplate/ContractTemplateSearchFields.vue
  src/views/customer/CustomerDetail.vue
  src/views/employee/EmployeeLayout.vue
  src/views/log/AccessLogView.vue
  src/views/notification/NotificationLayout.vue
  src/views/product/ProductList.vue
  src/views/sales/RegisterSales.vue
  src/views/sales/SalesView.vue
  src/views/salesDashboard/SalesDashboardLayout.vue
  src/views/support/notice/NoticeCreate.vue
  src/views/support/notice/NoticeDetail.vue
  src/views/support/notice/NoticeEdit.vue
  src/views/support/qna/QnaCreate.vue
  src/views/support/qna/QnaDetail.vue
  src/views/support/qna/QnaView.vue
  src/views/user/Mypage.vue
  vite.config.js
Labels: bug, enhancement

#185 [Env] https 도메인 등록
  server.js
  src/api/auth.js
Labels: enhancement

#187 [Refactor] 콘솔 로그 제거
  src/components/salesDashboard/YearSalesCard.vue
  src/stores/auth.js
  src/stores/notification.js
  src/views/notification/NotificationLayout.vue
  src/views/sales/SalesView.vue
  src/views/salesDashboard/SalesDashboardLayout.vue
Labels: enhancement

#188 [Refactor] : 계약 반려 적용
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#189 [Refactor] : 계약서 양식 기능오류 수정
  src/views/contract/ContractManagementView.vue
  src/views/contractTemplate/ContractTemplateUploadModal.vue
  src/views/contractTemplate/ContractTemplateView.vue
Labels: enhancement

#190 [Feat] 상담 관리 화면 구현 / [Refactor] 고객 관리 화면 구현
  src/api/auth.js
  src/api/consult.js
  src/api/customer.js
  src/components/consult/ConsultDetailModal.vue
  src/components/consult/ConsultSearch.vue
  src/components/consult/ConsultTable.vue
  src/config/menuConfig.js
  src/router/index.js
  src/views/consult/ConsultRegister.vue
  src/views/consult/ConsultingView.vue
  src/views/consulting/ConsultingView.vue
  src/views/customer/CustomerDetail.vue
  src/views/customer/CustomerRegister.vue
  src/views/customer/CustomerSearch.vue
  src/views/customer/CustomerTable.vue
  src/views/customer/CustomerView.vue
  vite.config.js
Labels: enhancement

#191 [Feat] 사원별 대시보드 페이지 생성
  src/components/dashboard/employee/MonthQuarterEmployeePerformanceCard.vue
  src/config/menuConfig.js
  src/views/dashboard/EmployeeDashboard.vue
  src/views/dashboard/ProductDashboard.vue
Labels: enhancement

#194 [Fix] 실적 목표 조회 안되는 문제 수정
  src/views/dashboard/EmployeeDashboard.vue
Labels: bug

#197 [Refactor] 상품 - S3 이미지 업로드 최적화 및 관리자 권한 분기처리
  server.js
  src/api/auth.js
  src/components/product/ImageUploadModal.vue
  src/components/product/ProductDetailForm.vue
  src/components/product/ProductRegisterConfirmModal.vue
  src/components/product/ProductRegisterForm.vue
  src/components/product/ProductUpdateConfirmModal.vue
  src/layouts/DefaultLayout.vue
  src/views/product/ProductDetail.vue
  src/views/product/ProductRegister.vue
Labels: enhancement

#200 [Refactor] 같은 브라우저 내에서 재로그인 시에 알림의 실시간 연결이 되지 않는 문제 해결
  server.js
  src/api/auth.js
  src/stores/notification.js
  src/views/user/LoginView.vue
  vite.config.js
Labels: bug

#202 [Env] URL 하드 코딩 변경
  server.js
  src/api/auth.js
  src/stores/notification.js
Labels: enhancement

#203 [Env] 로그 경로 수정
  src/stores/notification.js
  src/views/log/AccessLogView.vue
Labels: enhancement

#201 [Feat] 사원 대시보드 구현
  server.js
  src/main.js
  src/views/HomeView.vue
  src/views/dashboard/EmployeeDashboard.vue
Labels: enhancement

#207 [Refactor] 고객 상세 조회 화면 수정
  src/api/customer.js
  src/components/customer/CustomerSearchFields.vue
  src/router/index.js
  src/views/consult/ConsultDetailView.vue
  src/views/customer/CustomerDetail.vue
  src/views/customer/CustomerSearch.vue
  src/views/customer/CustomerTable.vue
  src/views/customer/CustomerView.vue
Labels: enhancement

#210 [Refactor] 고객 상세 화면에 '취소' 버튼 추가 및 피드백 반영
  src/components/consult/ConsultDetailModal.vue
  src/components/consult/ConsultSearchFields.vue
  src/components/customer/CustomerSearchFields.vue
  src/views/consult/ConsultDetailView.vue
  src/views/consult/ConsultRegister.vue
  src/views/consult/ConsultingView.vue
  src/views/customer/CustomerDetail.vue
  src/views/customer/CustomerView.vue
Labels: enhancement

#209 [Refactor] 상품 수정 페이지 개선
  src/components/product/ProductDeleteConfirmModal.vue
  src/components/product/ProductDetailForm.vue
  src/components/product/ProductRegisterCancelModal.vue
  src/components/product/ProductRegisterForm.vue
  src/views/product/ProductDetail.vue
  src/views/product/ProductList.vue
  src/views/product/ProductRegister.vue
  src/views/product/ProductUpdate.vue
Labels: enhancement

#211 feat : 대시보드 구현
  src/views/dashboard/EmployeeDashboard.vue
  src/views/user/LoginView.vue
Labels: enhancement

#213 [Refactor] 검색창 및 대시보드 여백 통일성 개선
  src/components/common/SearchFilterShell.vue
  src/views/salesDashboard/SalesDashboardLayout.vue
  vite.config.js
Labels: enhancement

#214 [Refactor] : 탭 전체 닫기 현재창 빼고 닫기 추가
  src/components/TopTabs.vue
  src/main.js
  src/stores/tabStore.js
Labels: enhancement

#216 [Refactor] 알림 sse 연결이 배포환경에서 끊어지는 문제 수정
  .gitignore
  server.js
  src/api/auth.js
  src/components/notification/NotificationDropdown.vue
  src/stores/notification.js
  src/views/salesDashboard/SalesDashboardLayout.vue
  vite.config.js
Labels: bug, enhancement

#219 [Refactor] 고객 피드백 점수 수정
  src/views/dashboard/EmployeeDashboard.vue
Labels: enhancement

#220 [Refactor] : QA 계약 관련 전체 수정
  src/components/contract/ContractDetailModal.vue
  src/components/contract/ContractSearchFields.vue
  src/views/contract/ContractManagementView.vue
  src/views/contractTemplate/ContractTemplateSearchFields.vue
  src/views/contractTemplate/ContractTemplateView.vue
Labels: enhancement

#222 [Refactor] 고객지원 파트 QA 반영
  src/components/qna/QnaList.vue
  src/views/support/notice/NoticeDetail.vue
  src/views/support/qna/QnaDetail.vue
Labels: enhancement

#223 [Refactor] 관리 탭과 매출 내역 탭 전반적인 스타일 수정 및 일부 기능 개선
  src/App.vue
  src/components/Header.vue
  src/components/approval/ApprovalSearchFields.vue
  src/components/common/SearchFilterShell.vue
  src/components/employee/DepartmentTreeNode.vue
  src/components/employee/EmployeeDepartmentList.vue
  src/components/employee/EmployeeSearchFields.vue
  src/components/employee/EmployeeSearchResult.vue
  src/components/sales/SalesSearchFields.vue
  src/main.js
  src/stores/departmentStore.js
  src/stores/notification.js
  src/views/contract/ContractApprovalRequestModal.vue
  src/views/employee/EmployeeLayout.vue
  src/views/notification/NotificationLayout.vue
  src/views/sales/RegisterSales.vue
  src/views/sales/SalesView.vue
  src/views/user/LoginView.vue
  src/views/user/Mypage.vue
Labels: enhancement

#232 [Refactor] 문의사항 필터링 시 1페이지로 가도록 수정
  src/components/qna/QnaList.vue
Labels: enhancement

#230 [Refactor] : 계약 상세 조회 페이지 수정
  src/components/contract/ContractDetailModal.vue
  src/router/index.js
  src/views/contract/ContractApprovalRequestModal.vue
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#237 [Fix] 상담, 고객 관리 화면 목록 출력되게 수정
  src/api/consult.js
  src/api/customer.js
  src/views/consult/ConsultingView.vue
  src/views/customer/CustomerView.vue
Labels: enhancement

#231 [Refactor] 개인 실적 목표, 팀 실적 목표 스타일 수정
  src/components/goal/DepartmentGoalSearchFields.vue
  src/components/goal/EmployeeGoalSearchFields.vue
  src/views/goal/DepartmentGoalList.vue
  src/views/goal/EmployeeGoalList.vue
Labels: enhancement

#234 [Refactor] 실적 목표 등록 / 수정 QA 적용
  src/views/goal/EmployeeGoalDetail.vue
  src/views/goal/EmployeeGoalRegister.vue
  src/views/goal/EmployeeGoalUpdate.vue
Labels: enhancement

#238 [Refactor] 사원 조회 페이지 로고 수정 및 알림 읽음 예외처리 추가, favicon 추가
  index.html
  public/close.svg
  public/favicon.svg
  public/open.svg
  src/components/TopTabs.vue
  src/components/employee/DepartmentTreeNode.vue
  src/views/notification/NotificationLayout.vue
  src/views/sales/RegisterSales.vue
Labels: enhancement

#240 [Style] 검색 필드 폰트 수정 및 모달 버튼 사이 간격 추가
  src/components/goal/DepartmentGoalSearchFields.vue
  src/components/goal/EmployeeGoalDeleteModal.vue
  src/components/goal/EmployeeGoalSearchFields.vue
  src/components/goal/GoalRegisterCancelModal.vue
  src/components/goal/GoalRegisterConfirmModal.vue
Labels: enhancement

#243 [Refactor] 상품 검색 필드 수정
  src/components/product/ProductSearchFields.vue
  src/views/product/ProductList.vue
Labels: enhancement

#244 [Refactor] : 전반적인 프론트 수정
  src/components/contract/ContractDetailModal.vue
  src/views/HomeView.vue
  src/views/contract/ContractManagementView.vue
Labels: enhancement

#245 [Hotfix] : 계약서 양식 관리 버튼 안보이는거 수정
  src/views/contractTemplate/ContractTemplateView.vue
Labels: bug
